version: '3.4'

services:
 Jewelry:
        container_name: SqlServerContainer
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
            - 8002:1433
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=myStong_Password123# 
 jewelryproductionorder:
    container_name: jewelryproductionorder
    image: ${DOCKER_REGISTRY-}jewelryproductionorder
    ports: 
    - 8001:80
    build:
      context: .
      dockerfile: JewelryProductionOrder/Dockerfile
    # environment:
    #   ConnectionStrings__DefaultConnection: "Server=Jewelry; Database=Jewelry; User Id=sa; Password=myStong_Password123#;Trust Server Certificate=True;"
    depends_on:
    - Jewelry
 dataaccess:
    image: dataaccess
    build:
      context: .
      dockerfile: JewelryProductionOrder.DataAccess/Dockerfile
 models:
    image: models
    build:
      context: .
      dockerfile: JewelryProductionOrder.Models/Dockerfile