// <auto-generated />
using System;
using JewelryProductionOrder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JewelryProductionOrder.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240726073128_newDatas")]
    partial class newDatas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GemstoneMaterialSet", b =>
                {
                    b.Property<int>("GemstonesId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialSetsId")
                        .HasColumnType("int");

                    b.HasKey("GemstonesId", "MaterialSetsId");

                    b.HasIndex("MaterialSetsId");

                    b.ToTable("GemstoneMaterialSet");
                });

            modelBuilder.Entity("JewelryProductionOrder.Models.BaseDesign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BaseDesigns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "\\Images\\Ring.webp",
                            Name = "Bezel Solitarie Engagement Ring",
                            Type = "Company"
                        },
                        new
                        {
                            Id = 2,
                            Image = "\\Images\\Pendant.jpg",
                            Name = "Diamond Reiki Symbol Pendant",
                            Type = "Company"
                        },
                        new
                        {
                            Id = 3,
                            Image = "\\Images\\Necklace.webp",
                            Name = "Smile Necklace",
                            Type = "Company"
                        },
                        new
                        {
                            Id = 4,
                            Image = "\\Images\\Band.webp",
                            Name = "Swirl Diamond Wedding Band",
                            Type = "Company"
                        });
                });

            modelBuilder.Entity("JewelryProductionOrder.Models.Delivery", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SalesStaffId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("JewelryId")
                        .HasColumnType("int");

                    b.Property<int>("WarrantyCardId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CustomerId", "SalesStaffId", "JewelryId", "WarrantyCardId");

                    b.HasIndex("JewelryId");

                    b.HasIndex("SalesStaffId");

                    b.HasIndex("WarrantyCardId");

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("JewelryProductionOrder.Models.Gemstone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Carat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Clarity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gemstones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Carat = 3m,
                            Clarity = "VS1",
                            Color = "White",
                            Cut = "Round",
                            Name = "Diamond",
                            Price = 2000m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 2,
                            Carat = 1.5m,
                            Clarity = "VVS1",
                            Color = "Red",
                            Cut = "Oval",
                            Name = "Ruby",
                            Price = 1500m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 3,
                            Carat = 1.8m,
                            Clarity = "VS2",
                            Color = "Blue",
                            Cut = "Princess",
                            Name = "Sapphire",
                            Price = 1800m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 4,
                            Carat = 2m,
                            Clarity = "VS2",
                            Color = "White",
                            Cut = "Emerald",
                            Name = "Diamond",
                            Price = 1800m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 5,
                            Carat = 1m,
                            Clarity = "VVS2",
                            Color = "White",
                            Cut = "Marquise",
                            Name = "Diamond",
                            Price = 1000m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 6,
                            Carat = 2.5m,
                            Clarity = "VS1",
                            Color = "Green",
                            Cut = "Cushion",
                            Name = "Emerald",
                            Price = 2500m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 7,
                            Carat = 1.2m,
                            Clarity = "SI1",
                            Color = "Purple",
                            Cut = "Heart",
                            Name = "Amethyst",
                            Price = 600m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 8,
                            Carat = 1.8m,
                            Clarity = "VS1",
                            Color = "Yellow",
                            Cut = "Oval",
                            Name = "Topaz",
                            Price = 800m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 9,
                            Carat = 1.9m,
                            Clarity = "VS2",
                            Color = "Blue",
                            Cut = "Marquise",
                            Name = "Aquamarine",
                            Price = 1100m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 10,
                            Carat = 1.4m,
                            Clarity = "VS1",
                            Color = "Red",
                            Cut = "Round",
                            Name = "Garnet",
                            Price = 700m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 11,
                            Carat = 1.5m,
                            Clarity = "SI1",
                            Color = "Green",
                            Cut = "Princess",
                            Name = "Peridot",
                            Price = 500m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 12,
                            Carat = 1.3m,
                            Clarity = "VS2",
                            Color = "Yellow",
                            Cut = "Emerald",
                            Name = "Citrine",
                            Price = 400m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 13,
                            Carat = 1.7m,
                            Clarity = "VS1",
                            Color = "Pink",
                            Cut = "Cushion",
                            Name = "Morganite",
                            Price = 1200m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 14,
                            Carat = 1.6m,
                            Clarity = "VS2",
                            Color = "Multi",
                            Cut = "Heart",
                            Name = "Opal",
                            Price = 900m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 15,
                            Carat = 1.3m,
                            Clarity = "VS1",
                            Color = "Red",
                            Cut = "Oval",
                            Name = "Spinel",
                            Price = 950m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 16,
                            Carat = 2m,
                            Clarity = "VS2",
                            Color = "Green",
                            Cut = "Round",
                            Name = "Tourmaline",
                            Price = 1000m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 17,
                            Carat = 1.8m,
                            Clarity = "VS1",
                            Color = "Blue",
                            Cut = "Marquise",
                            Name = "Tanzanite",
                            Price = 1300m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 18,
                            Carat = 1.2m,
                            Clarity = "VS2",
                            Color = "Blue",
                            Cut = "Princess",
                            Name = "Zircon",
                            Price = 450m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 19,
                            Carat = 1.5m,
                            Clarity = "SI1",
                            Color = "Green",
                            Cut = "Emerald",
                            Name = "Jade",
                            Price = 700m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 20,
                            Carat = 1.4m,
                            Clarity = "VS1",
                            Color = "Blue",
                            Cut = "Cushion",
                            Name = "Lapis",
                            Price = 550m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 21,
                            Carat = 1.3m,
                            Clarity = "VS2",
                            Color = "Blue",
                            Cut = "Heart",
                            Name = "Turquoise",
                            Price = 600m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 22,
                            Carat = 1.1m,
                            Clarity = "VS1",
                            Color = "White",
                            Cut = "Oval",
                            Name = "Moonstone",
                            Price = 400m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 23,
                            Carat = 1.2m,
                            Clarity = "SI1",
                            Color = "Black",
                            Cut = "Round",
                            Name = "Onyx",
                            Price = 350m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 24,
                            Carat = 1.5m,
                            Clarity = "VS2",
                            Color = "Green",
                            Cut = "Princess",
                            Name = "Alexandrite",
                            Price = 3000m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 25,
                            Carat = 1.0m,
                            Clarity = "VS1",
                            Color = "Orange",
                            Cut = "Emerald",
                            Name = "Carnelian",
                            Price = 200m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 26,
                            Carat = 1.7m,
                            Clarity = "VS2",
                            Color = "Pink",
                            Cut = "Cushion",
                            Name = "Kunzite",
                            Price = 850m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 27,
                            Carat = 1.3m,
                            Clarity = "VS1",
                            Color = "Blue",
                            Cut = "Heart",
                            Name = "Larimar",
                            Price = 400m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 28,
                            Carat = 1.2m,
                            Clarity = "SI1",
                            Color = "Green",
                            Cut = "Oval",
                            Name = "Malachite",
                            Price = 300m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 29,
                            Carat = 1.1m,
                            Clarity = "VS2",
                            Color = "Black",
                            Cut = "Round",
                            Name = "Obsidian",
                            Price = 200m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 30,
                            Carat = 1.0m,
                            Clarity = "VS1",
                            Color = "White",
                            Cut = "Round",
                            Name = "Pearl",
                            Price = 100m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 31,
                            Carat = 2m,
                            Clarity = "VS2",
                            Color = "Green",
                            Cut = "Marquise",
                            Name = "Beryl",
                            Price = 1300m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 32,
                            Carat = 1.3m,
                            Clarity = "SI1",
                            Color = "Green",
                            Cut = "Princess",
                            Name = "Bloodstone",
                            Price = 500m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 33,
                            Carat = 1.1m,
                            Clarity = "VS1",
                            Color = "Red",
                            Cut = "Emerald",
                            Name = "Coral",
                            Price = 400m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 34,
                            Carat = 1.0m,
                            Clarity = "VS2",
                            Color = "Black",
                            Cut = "Cushion",
                            Name = "Hematite",
                            Price = 300m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 35,
                            Carat = 1.4m,
                            Clarity = "VS1",
                            Color = "Blue",
                            Cut = "Heart",
                            Name = "Iolite",
                            Price = 700m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 36,
                            Carat = 1.0m,
                            Clarity = "SI1",
                            Color = "Red",
                            Cut = "Oval",
                            Name = "Jasper",
                            Price = 200m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 37,
                            Carat = 1.5m,
                            Clarity = "VS2",
                            Color = "Blue",
                            Cut = "Round",
                            Name = "Kyanite",
                            Price = 600m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 38,
                            Carat = 1.2m,
                            Clarity = "VS1",
                            Color = "Grey",
                            Cut = "Marquise",
                            Name = "Labradorite",
                            Price = 500m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 39,
                            Carat = 1.1m,
                            Clarity = "VS2",
                            Color = "Pink",
                            Cut = "Princess",
                            Name = "Rhodochrosite",
                            Price = 450m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 40,
                            Carat = 1.2m,
                            Clarity = "VS1",
                            Color = "Blue",
                            Cut = "Emerald",
                            Name = "Sodalite",
                            Price = 300m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 41,
                            Carat = 1.3m,
                            Clarity = "SI1",
                            Color = "Purple",
                            Cut = "Cushion",
                            Name = "Sugilite",
                            Price = 350m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 42,
                            Carat = 1.4m,
                            Clarity = "VS2",
                            Color = "Orange",
                            Cut = "Heart",
                            Name = "Sunstone",
                            Price = 400m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 43,
                            Carat = 1.1m,
                            Clarity = "VS1",
                            Color = "Brown",
                            Cut = "Oval",
                            Name = "TigersEye",
                            Price = 250m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 44,
                            Carat = 1.2m,
                            Clarity = "VS2",
                            Color = "Blue",
                            Cut = "Round",
                            Name = "Turquoise",
                            Price = 500m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 45,
                            Carat = 1.0m,
                            Clarity = "SI1",
                            Color = "Green",
                            Cut = "Marquise",
                            Name = "Unakite",
                            Price = 200m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 46,
                            Carat = 1.5m,
                            Clarity = "VS1",
                            Color = "Green",
                            Cut = "Princess",
                            Name = "Variscite",
                            Price = 600m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 47,
                            Carat = 1.6m,
                            Clarity = "VS2",
                            Color = "Blue",
                            Cut = "Emerald",
                            Name = "Zircon",
                            Price = 700m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 48,
                            Carat = 1.7m,
                            Clarity = "VS1",
                            Color = "Purple",
                            Cut = "Cushion",
                            Name = "Ametrine",
                            Price = 1000m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 49,
                            Carat = 1.8m,
                            Clarity = "VS2",
                            Color = "Blue",
                            Cut = "Heart",
                            Name = "Benitoite",
                            Price = 3000m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 50,
                            Carat = 1.2m,
                            Clarity = "VS1",
                            Color = "Blue",
                            Cut = "Oval",
                            Name = "Chalcedony",
                            Price = 450m,
                            Status = "Available"
                        });
                });

            modelBuilder.Entity("JewelryProductionOrder.Models.Jewelry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BaseDesignId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaterialSetId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProductionRequestId")
                        .HasColumnType("int");

                    b.Property<string>("ProductionStaffId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SalesStaffId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BaseDesignId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MaterialSetId");

                    b.HasIndex("ProductionRequestId");

                    b.HasIndex("ProductionStaffId");

                    b.HasIndex("SalesStaffId");

                    b.ToTable("Jewelries");
                });

            modelBuilder.Entity("JewelryProductionOrder.Models.JewelryDesign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DesignFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesignStaffId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JewelryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductionStaffId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DesignStaffId");

                    b.HasIndex("JewelryId");

                    b.HasIndex("ProductionStaffId");

                    b.ToTable("JewelryDesigns");
                });

            modelBuilder.Entity("JewelryProductionOrder.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Purity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "White",
                            Price = 100m,
                            Purity = "14K",
                            Type = "Gold"
                        },
                        new
                        {
                            Id = 2,
                            Color = "Rose",
                            Price = 50m,
                            Purity = "10K",
                            Type = "Gold"
                        },
                        new
                        {
                            Id = 3,
                            Color = "Yellow",
                            Price = 80m,
                            Purity = "18K",
                            Type = "Gold"
                        },
                        new
                        {
                            Id = 4,
                            Color = "Green",
                            Price = 90m,
                            Purity = "14K",
                            Type = "Gold"
                        },
                        new
                        {
                            Id = 5,
                            Color = "Silver",
                            Price = 60m,
                            Purity = "925",
                            Type = "Silver"
                        },
                        new
                        {
                            Id = 6,
                            Color = "Silver",
                            Price = 70m,
                            Purity = "999",
                            Type = "Silver"
                        },
                        new
                        {
                            Id = 7,
                            Color = "White",
                            Price = 120m,
                            Purity = "950",
                            Type = "Platinum"
                        },
                        new
                        {
                            Id = 8,
                            Color = "Red",
                            Price = 30m,
                            Purity = "99.9%",
                            Type = "Copper"
                        },
                        new
                        {
                            Id = 9,
                            Color = "Golden",
                            Price = 40m,
                            Purity = "60%",
                            Type = "Brass"
                        },
                        new
                        {
                            Id = 10,
                            Color = "Grey",
                            Price = 50m,
                            Purity = "99.9%",
                            Type = "Titanium"
                        },
                        new
                        {
                            Id = 11,
                            Color = "Silver",
                            Price = 45m,
                            Purity = "304",
                            Type = "Steel"
                        },
                        new
                        {
                            Id = 12,
                            Color = "Grey",
                            Price = 20m,
                            Purity = "99.9%",
                            Type = "Zinc"
                        },
                        new
                        {
                            Id = 13,
                            Color = "White",
                            Price = 150m,
                            Purity = "99.9%",
                            Type = "Rhodium"
                        },
                        new
                        {
                            Id = 14,
                            Color = "White",
                            Price = 100m,
                            Purity = "95%",
                            Type = "Palladium"
                        },
                        new
                        {
                            Id = 15,
                            Color = "Grey",
                            Price = 180m,
                            Purity = "99.9%",
                            Type = "Iridium"
                        });
                });

            modelBuilder.Entity("JewelryProductionOrder.Models.MaterialSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MaterialSets");
                });

            modelBuilder.Entity("JewelryProductionOrder.Models.MaterialSetMaterial", b =>
                {
                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialSetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaterialId", "MaterialSetId");

                    b.HasIndex("MaterialSetId");

                    b.ToTable("MaterialSetsMaterials");
                });

            modelBuilder.Entity("JewelryProductionOrder.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesStaffId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("SalesStaffId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("JewelryProductionOrder.Models.ProductionRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DesignStaffId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductionStaffId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SalesStaffId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DesignStaffId");

                    b.HasIndex("ProductionStaffId");

                    b.HasIndex("SalesStaffId");

                    b.ToTable("ProductionRequests");
                });

            modelBuilder.Entity("JewelryProductionOrder.Models.ProductionRequestDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseDesignId")
                        .HasColumnType("int");

                    b.Property<int>("ProductionRequestId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaseDesignId");

                    b.HasIndex("ProductionRequestId");

                    b.ToTable("ProductionRequestDetails");
                });

            modelBuilder.Entity("JewelryProductionOrder.Models.QuotationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("JewelryId")
                        .HasColumnType("int");

                    b.Property<decimal>("LaborPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ManagerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaterialSetId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SalesStaffId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("JewelryId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("MaterialSetId");

                    b.HasIndex("SalesStaffId");

                    b.ToTable("QuotationRequests");
                });

            modelBuilder.Entity("JewelryProductionOrder.Models.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseDesignId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BaseDesignId");

                    b.HasIndex("UserId");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("JewelryProductionOrder.Models.WarrantyCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("JewelryId")
                        .HasColumnType("int");

                    b.Property<string>("SalesStaffId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("JewelryId")
                        .IsUnique();

                    b.HasIndex("SalesStaffId");

                    b.ToTable("WarrantyCards");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("JewelryProductionOrder.Models.User", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("GemstoneMaterialSet", b =>
                {
                    b.HasOne("JewelryProductionOrder.Models.Gemstone", null)
                        .WithMany()
                        .HasForeignKey("GemstonesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JewelryProductionOrder.Models.MaterialSet", null)
                        .WithMany()
                        .HasForeignKey("MaterialSetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JewelryProductionOrder.Models.Delivery", b =>
                {
                    b.HasOne("JewelryProductionOrder.Models.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JewelryProductionOrder.Models.Jewelry", "Jewelry")
                        .WithMany()
                        .HasForeignKey("JewelryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JewelryProductionOrder.Models.User", "SalesStaff")
                        .WithMany()
                        .HasForeignKey("SalesStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JewelryProductionOrder.Models.WarrantyCard", "WarrantyCard")
                        .WithMany()
                        .HasForeignKey("WarrantyCardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Jewelry");

                    b.Navigation("SalesStaff");

                    b.Navigation("WarrantyCard");
                });

            modelBuilder.Entity("JewelryProductionOrder.Models.Jewelry", b =>
                {
                    b.HasOne("JewelryProductionOrder.Models.BaseDesign", "BaseDesign")
                        .WithMany()
                        .HasForeignKey("BaseDesignId");

                    b.HasOne("JewelryProductionOrder.Models.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JewelryProductionOrder.Models.MaterialSet", "MaterialSet")
                        .WithMany("Jewelries")
                        .HasForeignKey("MaterialSetId");

                    b.HasOne("JewelryProductionOrder.Models.ProductionRequest", "ProductionRequest")
                        .WithMany("Jewelries")
                        .HasForeignKey("ProductionRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JewelryProductionOrder.Models.User", "ProductionStaff")
                        .WithMany()
                        .HasForeignKey("ProductionStaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JewelryProductionOrder.Models.User", "SalesStaff")
                        .WithMany()
                        .HasForeignKey("SalesStaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseDesign");

                    b.Navigation("Customer");

                    b.Navigation("MaterialSet");

                    b.Navigation("ProductionRequest");

                    b.Navigation("ProductionStaff");

                    b.Navigation("SalesStaff");
                });

            modelBuilder.Entity("JewelryProductionOrder.Models.JewelryDesign", b =>
                {
                    b.HasOne("JewelryProductionOrder.Models.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JewelryProductionOrder.Models.User", "DesignStaff")
                        .WithMany()
                        .HasForeignKey("DesignStaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JewelryProductionOrder.Models.Jewelry", "Jewelry")
                        .WithMany("JewelryDesigns")
                        .HasForeignKey("JewelryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JewelryProductionOrder.Models.User", "ProductionStaff")
                        .WithMany()
                        .HasForeignKey("ProductionStaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("DesignStaff");

                    b.Navigation("Jewelry");

                    b.Navigation("ProductionStaff");
                });

            modelBuilder.Entity("JewelryProductionOrder.Models.MaterialSetMaterial", b =>
                {
                    b.HasOne("JewelryProductionOrder.Models.Material", "Material")
                        .WithMany("MaterialSetMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JewelryProductionOrder.Models.MaterialSet", "MaterialSet")
                        .WithMany("MaterialSetMaterials")
                        .HasForeignKey("MaterialSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("MaterialSet");
                });

            modelBuilder.Entity("JewelryProductionOrder.Models.Post", b =>
                {
                    b.HasOne("JewelryProductionOrder.Models.User", "SalesStaff")
                        .WithMany()
                        .HasForeignKey("SalesStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalesStaff");
                });

            modelBuilder.Entity("JewelryProductionOrder.Models.ProductionRequest", b =>
                {
                    b.HasOne("JewelryProductionOrder.Models.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JewelryProductionOrder.Models.User", "DesignStaff")
                        .WithMany()
                        .HasForeignKey("DesignStaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JewelryProductionOrder.Models.User", "ProductionStaff")
                        .WithMany()
                        .HasForeignKey("ProductionStaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JewelryProductionOrder.Models.User", "SalesStaff")
                        .WithMany()
                        .HasForeignKey("SalesStaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("DesignStaff");

                    b.Navigation("ProductionStaff");

                    b.Navigation("SalesStaff");
                });

            modelBuilder.Entity("JewelryProductionOrder.Models.ProductionRequestDetail", b =>
                {
                    b.HasOne("JewelryProductionOrder.Models.BaseDesign", "BaseDesign")
                        .WithMany()
                        .HasForeignKey("BaseDesignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JewelryProductionOrder.Models.ProductionRequest", "ProductionRequest")
                        .WithMany("ProductionRequestDetails")
                        .HasForeignKey("ProductionRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseDesign");

                    b.Navigation("ProductionRequest");
                });

            modelBuilder.Entity("JewelryProductionOrder.Models.QuotationRequest", b =>
                {
                    b.HasOne("JewelryProductionOrder.Models.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("JewelryProductionOrder.Models.Jewelry", "Jewelry")
                        .WithMany("QuotationRequests")
                        .HasForeignKey("JewelryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JewelryProductionOrder.Models.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JewelryProductionOrder.Models.MaterialSet", "MaterialSet")
                        .WithMany()
                        .HasForeignKey("MaterialSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JewelryProductionOrder.Models.User", "SalesStaff")
                        .WithMany()
                        .HasForeignKey("SalesStaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Jewelry");

                    b.Navigation("Manager");

                    b.Navigation("MaterialSet");

                    b.Navigation("SalesStaff");
                });

            modelBuilder.Entity("JewelryProductionOrder.Models.ShoppingCart", b =>
                {
                    b.HasOne("JewelryProductionOrder.Models.BaseDesign", "BaseDesign")
                        .WithMany()
                        .HasForeignKey("BaseDesignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JewelryProductionOrder.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseDesign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JewelryProductionOrder.Models.WarrantyCard", b =>
                {
                    b.HasOne("JewelryProductionOrder.Models.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JewelryProductionOrder.Models.Jewelry", "Jewelry")
                        .WithOne("WarrantyCard")
                        .HasForeignKey("JewelryProductionOrder.Models.WarrantyCard", "JewelryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JewelryProductionOrder.Models.User", "SalesStaff")
                        .WithMany()
                        .HasForeignKey("SalesStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Jewelry");

                    b.Navigation("SalesStaff");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JewelryProductionOrder.Models.Jewelry", b =>
                {
                    b.Navigation("JewelryDesigns");

                    b.Navigation("QuotationRequests");

                    b.Navigation("WarrantyCard");
                });

            modelBuilder.Entity("JewelryProductionOrder.Models.Material", b =>
                {
                    b.Navigation("MaterialSetMaterials");
                });

            modelBuilder.Entity("JewelryProductionOrder.Models.MaterialSet", b =>
                {
                    b.Navigation("Jewelries");

                    b.Navigation("MaterialSetMaterials");
                });

            modelBuilder.Entity("JewelryProductionOrder.Models.ProductionRequest", b =>
                {
                    b.Navigation("Jewelries");

                    b.Navigation("ProductionRequestDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
